# S02 T02: Estructura d'una Matriu
## Luis Pardina - Data Science - 29/03/2022

***- Exercici 1***: Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. . 

In [1]:
import numpy as np
from numpy import random

#genero una array dtype int64 amb l'ajuda de random per generar 10 sencers entre 0 i 49
matriu = np.array(random.randint(50, size=(10)), dtype= 'int64')

print("Hem creat la matriu:\n", matriu)
print("Dimensió:", matriu.ndim)            #atribut ndim dóna dimensió de la matriu
print("Forma: ", matriu.shape)             #atribut shape dóna forma de la matriu

Hem creat la matriu:
 [29 48 21  1 21 16 28 17 10 44]
Dimensió: 1
Forma:  (10,)


***- Exercici 2***: De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu

In [2]:
mitja = np.mean(matriu)                    #càlcul del valor mig
print("\nMitja:", mitja)
for (i,v) in enumerate(matriu):
    matriu[i] = v - int(mitja)             #a cada escalar li resto la mitja
print("Valor menys mitja", matriu)   


Mitja: 23.5
Valor menys mitja [  6  25  -2 -22  -2  -7   5  -6 -13  21]


***- Exercici 3***: Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [3]:
#genero una array dtype int64 amb l'ajuda de random per generar 25 sencers entre 0 i 49
matriu1d = np.array(random.randint(200, size=(25)), dtype= 'int64')
aux = matriu1d.reshape(5,5)   #aprofito mètode reshape per a generar una vista de 5 x 5
matriu2d = aux.copy()
print("\nMatriu 5 x 5:\n", matriu2d)

max = matriu2d[0,0]
for x in np.nditer(matriu2d):               #itero per tots els escalars de la matriu
    if x > max: max = x
print("El valor màxim de la matriu és {0}".format(max))

for i, v in enumerate(matriu2d):
    print("Fila {0} màxim: {1}".format(i, v.max()))
    
transpuesta = np.transpose(matriu2d)        #trasposo i repeteixo el codi anterior
for i, v in enumerate(transpuesta):
    print("Columna {0} màxim: {1}".format(i, v.max()))


Matriu 5 x 5:
 [[ 48  76  96  91 186]
 [ 57  62 187 158   5]
 [195  32 185  85  22]
 [ 76  11 191  82  61]
 [ 26  34  40 140   1]]
El valor màxim de la matriu és 195
Fila 0 màxim: 186
Fila 1 màxim: 187
Fila 2 màxim: 195
Fila 3 màxim: 191
Fila 4 màxim: 140
Columna 0 màxim: 195
Columna 1 màxim: 76
Columna 2 màxim: 191
Columna 3 màxim: 158
Columna 4 màxim: 186
