# S02 T02: Estructura d'una Matriu
## Luis Pardina - Data Science - 29/03/2022

***- Exercici 1***: Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. . 

In [7]:
import numpy as np
from numpy import random

#genero una array dtype int64 amb l'ajuda de random amb n sencers entre 0 i 49
n = random.randint(10,20)   # n entre 10 i 19
matriu = np.array(random.randint(50, size=(n)), dtype= 'int64')

print("Hem creat la matriu:\n", matriu)
print("Dimensió:", matriu.ndim)            #atribut ndim dóna dimensió de la matriu
print("Forma: ", matriu.shape)             #atribut shape dóna forma de la matriu

Hem creat la matriu:
 [ 8 30 30 45 15  7 41 49 39  4 26 14 42 11  1 12]
Dimensió: 1
Forma:  (16,)


***- Exercici 2***: De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu

In [8]:
mitja = matriu.mean()                      #càlcul del valor mig amb mètode mean
print("\nMitja:", mitja)
matriu = matriu - mitja                    #a cada escalar li restem la mitja
print("Valor menys mitja", matriu)   


Mitja: 23.375
Valor menys mitja [-15.375   6.625   6.625  21.625  -8.375 -16.375  17.625  25.625  15.625
 -19.375   2.625  -9.375  18.625 -12.375 -22.375 -11.375]


***- Exercici 3***: Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [4]:
#genero una array dtype int64 amb l'ajuda de random per generar 25 sencers entre 0 i 199
matriu_1d = np.array(random.randint(200, size=(25)), dtype= 'int64')
aux = matriu_1d.reshape(5,5)   #aprofito mètode reshape per a generar una vista de 5 x 5
matriu_2d = aux.copy()         #‼faig copia de la vista

print("\nMatriu 5 x 5:\n", matriu_2d)
print("\nEl valor màxim de la matriu és {0}".format(matriu_2d.max()))  #mètode max
print("Eix 0 màxims: {0}".format(matriu_2d.max(axis=0)))               #mètode max axis 0  
print("Eix 1 màxims: {0}".format(matriu_2d.max(axis=1)))               #mètode max axis 1


Matriu 5 x 5:
 [[ 74 187 166 189  71]
 [179   9 172 164  95]
 [ 81 171 124  88 119]
 [ 53 141 187 187  25]
 [142  69 188 195  75]]

El valor màxim de la matriu és 195
Eix 0 màxims: [179 187 188 195 119]
Eix 1 màxims: [189 179 171 187 195]


***Exercici 5***: Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [10]:
fila = 2                 #selecciono la tercera fila
columna = 3              #selecciono la quarta columna
suma_fila = 0
suma_columna = 0

for y in matriu_2d[fila,:]:
    suma_fila += y
for x in matriu_2d[:,columna]:
    suma_columna += x
print("La suma de la fila {0} i la columna {1} dóna {2}".format(fila, columna, suma_fila + suma_columna))

La suma de la fila 2 i la columna 3 dóna 1406


***Exercici 6***: Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre. Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul

In [12]:
print(matriu_2d %4 == 0)

[[False False False False False]
 [False False  True  True False]
 [False False  True  True False]
 [False False False False False]
 [False False  True False False]]


***Exercici 7***: A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant

In [13]:
print(matriu_2d[matriu_2d % 4 == 0])

[172 164 124  88 188]
